name             'dani-serv'
maintainer       'James Awesome'
maintainer_email 'james@wesome.nyc'
license          'All rights reserved'
description      'Installs/Configures dani-serv'
long_description 'Installs/Configures dani-serv'
version          '0.1.0'
