name             'dani-serv'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures dani-serv'
long_description 'Installs/Configures dani-serv'
version          '0.1.0'
